repos:
- hooks:
  - id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 23.7.0
- hooks:
  - id: ruff
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.284
